-- DROP DATABASE IF EXISTS related_queries_db;
--
-- CREATE DATABASE related_queries_db;
--
-- USE related_queries_db;
--
-- DROP TABLE IF EXISTS iphone;
--
-- CREATE TABLE iPhone(
-- 	 id INTEGER(11) AUTO_INCREMENT NOT NULL,
-- 	 query VARCHAR(40) NOT NULL,
-- 	 value INTEGER(100) NOT NULL,
-- 	 PRIMARY KEY(id)
-- );
--
-- DROP TABLE IF EXISTS iphone_cities;
--
-- CREATE TABLE iphone_cities(
-- 	id INTEGER(11) AUTO_INCREMENT NOT NULL,
-- 	city VARCHAR(20) NOT NULL,
-- 	value INTEGER(100) NOT NULL,
-- 	PRIMARY KEY(id)
-- );
--
-- DROP TABLE IF EXISTS craft_beer;
--
-- CREATE TABLE craft_beer(
-- 	id INTEGER(11) AUTO_INCREMENT NOT NULL,
-- 	query VARCHAR(20) NOT NULL,
-- 	value INTEGER(100) NOT NULL,
-- 	PRIMARY KEY(id)
-- );
--
-- DROP TABLE IF EXISTS craft_beer_cities;
--
-- CREATE TABLE craft_beer_cities(
-- 	id INTEGER(11) AUTO_INCREMENT NOT NULL,
-- 	city VARCHAR(20) NOT NULL,
-- 	value INTEGER(100) NOT NULL,
-- 	PRIMARY KEY(id)
-- );
--
-- DROP TABLE IF EXISTS shirt;
--
-- CREATE TABLE shirt(
-- 	id INTEGER(11) AUTO_INCREMENT NOT NULL,
-- 	query VARCHAR(20) NOT NULL,
-- 	value INTEGER(100) NOT NULL,
-- 	PRIMARY KEY(id)
-- );
--
-- DROP TABLE IF EXISTS shirt_cities;
--
-- CREATE TABLE shirt_cities(
-- 	id INTEGER(11) AUTO_INCREMENT NOT NULL,
-- 	city VARCHAR(20) NOT NULL,
-- 	value INTEGER(100) NOT NULL,
-- 	PRIMARY KEY(id)
-- );
